name: lets_chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.3
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  emoji_picker_flutter: ^2.1.0
  google_generative_ai: ^0.2.0
  flutter_markdown:
  url_launcher: ^6.2.4
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  firebase_messaging: ^14.7.16
  firebase_messaging_web: ^3.6.6
  http: ^1.2.0
  flutter_notification_channel: ^2.0.0
  image_gallery_saver: ^2.0.3
  curved_navigation_bar: ^1.0.3
  contacts_service: ^0.6.3
  permission_handler: ^11.3.0
  dio: ^4.0.0
  path_provider: ^2.0.2
  zego_uikit_prebuilt_call: ^4.3.2
  zego_uikit_prebuilt_video_conference: ^2.6.9
  zego_uikit_prebuilt_live_audio_room: ^3.4.0
  razorpay_flutter: ^1.3.6
  fluttertoast: ^8.2.4
  zego_uikit_signaling_plugin: ^2.7.6
  translator: ^1.0.0
  flutter_local_notifications: ^17.0.0
  pdf: ^3.10.8
  share_plus: ^8.0.2
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_windowmanager: ^0.2.0
  introduction_screen: ^3.1.14
  image_to_pdf_converter: ^0.0.1
  get: ^4.6.5
  dotted_border: ^2.0.0+2
  open_filex: ^4.1.1
  flutter_share: ^2.0.0
  story_view: ^0.16.5
  shared_preferences: ^2.2.2
  local_auth: ^2.2.0
  go_router: ^13.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_bloc: ^8.1.3
  flutter_quill: ^9.2.10
  google_nav_bar: ^5.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/chat.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
